version: "3.3"

services:
  pyspark-app:
    build:
      context: ./pyspark/
      dockerfile: Dockerfile
    environment:
      - SPARK_MASTER=spark://spark:7077
    depends_on:
      - spark
      - spark-worker
    ports:
      - "8000:8000"
  spark:
    extends:
      file: ./pyspark/docker-compose-spark.yml
      service: spark
  spark-worker:
    extends:
      file: ./pyspark/docker-compose-spark.yml
      service: spark-worker
  mongo:
    extends:
      file: ./mongo/docker-compose-mongo.yml
      service: mongo
  mongo-express:
    extends:
      file: ./mongo/docker-compose-mongo.yml
      service: mongo-express
