name: CI with Python TestUnit
on:
  push:
    branches:
      - "*"
    branches-ignore:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: cd pyspark && pip install -r requirements.txt
      - name: Run tests
        run: cd pyspark/app && python -m unittest test_script.py
